changes to episode 6, tasks 1-9
carpentries-incubator/high-dimensional-stats-r pull request #147
Opened 2024-03-06 14:39 UTC by mallewellyn

Largely re-writing motivation and methodology sections in line with tasks 1-9 of #119 

Particularly tries to clarify the differences between clustering and PCA/FA from the outset (even though they're completely different methods, I think a reader would benefit from this being apparent immediately).

Also moves the section on believing in clusters to after the method is explained - I think how to believe in a cluster is easier to understand if we know what clusters are fully first

2024-03-15 12:18 UTC, alanocallaghan commented on _episodes_rmd/06-k-means.Rmd
> +knitr::include_graphics("../fig/kmeans.gif")
```suggestion
knitr::include_graphics(here::here("fig/kmeans.gif"))
```

2024-03-18 20:31 UTC, alanocallaghan commented on _episodes_rmd/06-k-means.Rmd
> +knitr::include_graphics(here::here("fig/kmeans.gif"))
knitr::include_graphics("../fig/kmeans.gif")

2024-03-25 15:27 UTC, alanocallaghan requested changes
Looks great just minor problems

2024-03-25 15:27 UTC, alanocallaghan commented on _episodes_rmd/06-k-means.Rmd
> +within-cluster variation adn thus the amount that
adn -> and

2024-03-25 15:27 UTC, alanocallaghan commented on _episodes_rmd/06-k-means.Rmd
> +2. Update centroid positions as the average of the points in that cluster
```suggestion
2. Update centroid positions as the average of the points in that cluster.
```

2024-03-25 15:27 UTC, alanocallaghan commented on _episodes_rmd/06-k-means.Rmd
> +to understand), it does have some disadvantages, namely difficulties in identifying
namely -> particularly

(just so we're not implying these are the only ones)

2024-03-25 15:27 UTC, alanocallaghan commented on _episodes_rmd/06-k-means.Rmd
> +initial clusters which observations belong to and the need for the user to specifiy the
specifiy -> specify

2024-03-25 15:32 UTC, mallewellyn commented on _episodes_rmd/06-k-means.Rmd
> +within-cluster variation adn thus the amount that
7f7b8ff

2024-03-25 15:32 UTC, mallewellyn commented on _episodes_rmd/06-k-means.Rmd
> +to understand), it does have some disadvantages, namely difficulties in identifying
ee8917a

2024-03-25 15:33 UTC, mallewellyn commented on _episodes_rmd/06-k-means.Rmd
> +initial clusters which observations belong to and the need for the user to specifiy the
67a85aa

2024-03-25 15:33 UTC, mallewellyn commented
All fixed above :)

2024-03-25 15:34 UTC, alanocallaghan approved these changes

2024-03-25 15:34 UTC, alanocallaghan commented
Awesome thanks, great addition

2024-03-25 15:34 UTC, merged