changes to episode 7, tasks 25-32
carpentries-incubator/high-dimensional-stats-r pull request #151
Opened 2024-03-08 13:55 UTC by mallewellyn

Very minor changes, but a lot of alt text and captions added!

tasks 25-32 #120

2024-03-08 14:26 UTC, alanocallaghan requested changes
Looks good, mostly minor edits

If you want to be a real accessibility hero, we should probably also add captions/alt text for the challenge plots

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r hclustfig1, echo=FALSE, out.width="500px", fig.cap="Example data showing two clusters of observation pairs.", fig.alt="Scatter plot of observations x2 versus x1. Two clusters of pairs of observ
"the space"?

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r hclustfig2, echo=FALSE, out.width="500px", fig.cap="Example data showing fusing of one observation into larger cluster.", fig.alt="Scatter plot of observations x2 versus x1. Three boxes are sho
again "the space"? may be a simpler way to phrase this

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r, fig.cap="Heat map of methylation data.", fig.alt="Heat map of individual versus methylation sides, coloured by methylation level. Red delineates high methylation levels (up to around 4) and bl
There is no plot for this block, remove the caption/alt text

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r heatmap-noclust, echo=FALSE, fig.cap="Heat map of methylation data.", fig.alt="Heat map of individual versus methylation sides, coloured by methylation level. Red delineates high methylation le
Heat map -> heatmap

sides -> sites

Suggest "heatmap of methylation level, with individuals along the y-axis and methylation sites along the x-axis"

"Red colours indicate high methylation levels..." (similar with blue)

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r heatmap-clust, fig.cap="Heat map of methylation data clustered by methylation sites and individuals.", fig.alt="Heat map of individual versus methylation sides, coloured by methylation level. R
Similar comments to above

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r cutree, fig.cap="Scatter plot of data x2 versus x1, coloured by cluster.", fig.alt="A scatter plot of the example data x2 versus x1, coloured by 8 different clusters. There are two clusters in
Suggest using "top left" etc rather than "north west"

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r plot-clust-method, fig.cap="Dendogram with boxes around clusters.", fig.alt="A dendogram for the methyl_mat data with boxes overlain on clusters. There are 5 clusters in total, each delineating
overlain -> overlaid

5 clusters delineating clusters sounds a bit circular

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r plot-clust-method, fig.cap="Dendogram with boxes around clusters.", fig.alt="A dendogram for the methyl_mat data with boxes overlain on clusters. There are 5 clusters in total, each delineating
Boxes delineating clusters?

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r heatmap-cor-example, fig.cap="Heat map of simulated data.", fig.alt="Heat map of simulated data: feature versus sample. The grid cells of the heat map are coloured from red (high) to blue (low)
heatmap

2024-03-08 14:26 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r heatmap-cor-cor-example, fig.cap="Heat maps of features versus samples clustered in the samples according to correlation.", fig.alt="Heat maps of features versus samples, coloured by simulated
heatmaps

2024-03-08 15:40 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r hclustfig1, echo=FALSE, out.width="500px", fig.cap="Example data showing two clusters of observation pairs.", fig.alt="Scatter plot of observations x2 versus x1. Two clusters of pairs of observ
Have changed to "close in x and y distance". Can we do better?

2024-03-08 15:44 UTC, alanocallaghan commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r hclustfig1, echo=FALSE, out.width="500px", fig.cap="Example data showing two clusters of observation pairs.", fig.alt="Scatter plot of observations x2 versus x1. Two clusters of pairs of observ
That sounds reasonable to me! But open to other ideas for sure

2024-03-08 15:53 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r hclustfig2, echo=FALSE, out.width="500px", fig.cap="Example data showing fusing of one observation into larger cluster.", fig.alt="Scatter plot of observations x2 versus x1. Three boxes are sho
Changed to "Blue and red boxes contain two observations each. The two boxes contain points that are relatively far apart."

2024-03-08 15:55 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r heatmap-noclust, echo=FALSE, fig.cap="Heat map of methylation data.", fig.alt="Heat map of individual versus methylation sides, coloured by methylation level. Red delineates high methylation le
```suggestion
```{r heatmap-noclust, echo=FALSE, fig.cap="Heat map of methylation data.", fig.alt="Heatmap of methylation level with individuals along the y axis and methylation sites along the x axis. Red colours indicate high methylation levels (up to around 4), blue colours indicate low methylation levels (to around -4) and white indicates methylation levels close to zero. There are many vertical blue and red stripes."}
```

2024-03-08 15:57 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r, fig.cap="Heat map of methylation data.", fig.alt="Heat map of individual versus methylation sides, coloured by methylation level. Red delineates high methylation levels (up to around 4) and bl
Oops! Changed!

2024-03-08 16:00 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r heatmap-clust, fig.cap="Heat map of methylation data clustered by methylation sites and individuals.", fig.alt="Heat map of individual versus methylation sides, coloured by methylation level. R
Changed!

2024-03-08 16:02 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r cutree, fig.cap="Scatter plot of data x2 versus x1, coloured by cluster.", fig.alt="A scatter plot of the example data x2 versus x1, coloured by 8 different clusters. There are two clusters in
Fair point - apparently I thought we were trying to navigate to the clusters

2024-03-08 16:04 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r plot-clust-method, fig.cap="Dendogram with boxes around clusters.", fig.alt="A dendogram for the methyl_mat data with boxes overlain on clusters. There are 5 clusters in total, each delineating
```suggestion
```{r plot-clust-method, fig.cap="Dendogram with boxes around clusters.", fig.alt="A dendogram for the methyl_mat data with boxes overlaid on clusters. There are 5 boxes in total, each indicating separate clusters."}
```

2024-03-08 16:05 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r heatmap-cor-cor-example, fig.cap="Heat maps of features versus samples clustered in the samples according to correlation.", fig.alt="Heat maps of features versus samples, coloured by simulated
likewise

2024-03-08 16:07 UTC, mallewellyn commented
Fair point re the alt text for challenges. Haven't done this for any episodes so will make a note in the issue.

2024-03-08 16:08 UTC, alanocallaghan commented
Yeah no rush on the challenges, priority is definitely to do the lesson material first

2024-03-21 17:06 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +```{r heatmap-noclust, echo=FALSE, fig.cap="Heat map of methylation data.", fig.alt="Heat map of individual versus methylation sides, coloured by methylation level. Red delineates high methylation le
f58a447

2024-03-25 14:32 UTC, mallewellyn commented
In your PR #166

2024-03-25 14:41 UTC, alanocallaghan commented
Good spot yeah thanks. Should have pinged you about it at the time

2024-03-25 14:56 UTC, mallewellyn commented
No worries! Realised as I was going through anyway!

2024-03-25 14:58 UTC, mallewellyn commented on _episodes_rmd/07-hierarchical.Rmd
> +distance functions in functions that perform hierarchical clustering, such as
changed in commit below

2024-03-25 15:12 UTC, alanocallaghan approved these changes

2024-03-25 15:22 UTC, merged