Update 02-high-dimensional-regression.Rmd
carpentries-incubator/high-dimensional-stats-r pull request #68
Opened 2022-06-07 13:51 UTC by hannesbecher

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

2022-06-07 21:19 UTC, catavallejos requested changes

2022-06-08 10:01 UTC, catavallejos requested changes

2022-06-13 10:27 UTC, hannesbecher commented on _episodes_rmd/02-high-dimensional-regression.Rmd
> +that carries a methyl mark. In this case, the methylation data come in
Happy with that

2022-06-13 10:32 UTC, hannesbecher reviewed
I've committed Cata's changes

2022-06-13 10:33 UTC, catavallejos approved these changes

2022-06-13 10:34 UTC, catavallejos commented
Thanks @hannesbecher I will merge once the checks are completed.

2022-06-14 08:21 UTC, merged