Structural updates to PCA
carpentries-incubator/high-dimensional-stats-r pull request #98
Opened 2023-02-02 21:11 UTC by hannesbecher

Several structural updates to the PCA episode as discussed with Cata.

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

2023-02-02 21:34 UTC, hannesbecher commented
Added changes to FA and k-means clustering

2023-02-02 22:06 UTC, catavallejos requested changes
Thanks for doing these edits, looks great. Here are my comments about the PCA episode.

2023-02-02 22:06 UTC, catavallejos commented on _episodes_rmd/04-principal-component-analysis.Rmd
>  > > ```{r pca-biplot-ex2, fig.cap="Caption", fig.cap="Alt"}
earlier you mention that users may want to specify the library when using `biplot()`. We should be consistent about that or explain why it may not be needed in this specific case.

2023-02-02 22:19 UTC, catavallejos requested changes
Comments for the FA episode.

2023-02-02 22:19 UTC, catavallejos commented on _episodes_rmd/05-factor-analysis.Rmd
> +represented by which latent factor(s). The fit of the CFA is then assessed.
In line 66 below, should "Another example of how FA" be "Another example of how CFA instead"?

2023-02-02 22:19 UTC, catavallejos commented on _episodes_rmd/05-factor-analysis.Rmd
> +* Confirmatory FA can be used to test hypotheses.
Why is line 98 a disadvantage? Seems to be stating a fact about popularity instead.

2023-02-02 22:19 UTC, catavallejos commented on _episodes_rmd/05-factor-analysis.Rmd
> +Similar to a biplot as we produced in the PCR episode, we can “plot the
Replace PCR by PCA :-)

2023-02-02 22:57 UTC, catavallejos commented
k-means edits, look good no comments about that.

2023-02-03 08:34 UTC, hannesbecher commented on _episodes_rmd/04-principal-component-analysis.Rmd
> +is also called a scree plot. NB, the amount of variance accounted for by a principal
OK

2023-02-03 08:36 UTC, hannesbecher commented on _episodes_rmd/04-principal-component-analysis.Rmd
> +variance decreases more slowly. This is sometimes interpreted as structural variance
Agreed.

2023-02-03 08:37 UTC, hannesbecher commented on _episodes_rmd/04-principal-component-analysis.Rmd
> +*principal component scores* and the *loadings*. The matrix of PC scores
OK

2023-02-03 08:44 UTC, hannesbecher commented on _episodes_rmd/04-principal-component-analysis.Rmd
> +The rotation matrix has as many rows as there are features in the original data.
changed

2023-02-03 08:44 UTC, hannesbecher commented on _episodes_rmd/04-principal-component-analysis.Rmd
> +The PC scores are obtained by carrying out matrix multiplication of the
ok

2023-02-03 08:44 UTC, hannesbecher commented on _episodes_rmd/04-principal-component-analysis.Rmd
> +> # NB, axis orientations may be swapped but the relative positions of the dots should be the same in both plots.
changed

2023-02-03 08:44 UTC, hannesbecher commented on _episodes_rmd/04-principal-component-analysis.Rmd
>  > > ```{r pca-biplot-ex2, fig.cap="Caption", fig.cap="Alt"}
mad specific

2023-02-03 08:46 UTC, hannesbecher commented on _episodes_rmd/05-factor-analysis.Rmd
> +represented by which latent factor(s). The fit of the CFA is then assessed.
CHanged

2023-02-03 08:49 UTC, hannesbecher commented on _episodes_rmd/05-factor-analysis.Rmd
> +* Confirmatory FA can be used to test hypotheses.
You are right, it is. One could argue that the fact it is not so popular/well adopted could be a disadvantage as reviers may not understand it etc.
Anyway I've removed this.

2023-02-03 08:50 UTC, hannesbecher reviewed
Thanks for pointing out these. I agree and am going to update the PR.

2023-02-03 08:58 UTC, hannesbecher commented
I see, I don't have to update the PR, but my new commit show here automatically. Ready for your review, @catavallejos

2023-02-03 13:39 UTC, catavallejos approved these changes

2023-02-03 13:39 UTC, merged